version: '3.3'

services:
  tabby:
    build:
      context: ..
      args:
        PYPI_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    environment:
      UVICORN_RELOAD: true
      VECTOR_WATCH_CONFIG: true
      STREAMLIT_RUN_ON_SAVE: true
    volumes:
      - ../:/app
      - ../deployment/scripts/tabby.sh:/usr/bin/tabby.sh:ro
