version: '3.3'

services:
  tabby:
    shm_size: 1gb
    environment:
      MODEL_BACKEND: triton
      MODEL_REPLICA: ${MODEL_REPLICA:-1}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
