version: '3.5'

services:
  scheduler:
    image: tabbyml/tabby
    platform: linux/amd64
    command: scheduler --now
    volumes:
      - "$HOME/.tabby:/data"

  tabby:
    depends_on:
      - scheduler
    restart: always
    image: tabbyml/tabby
    platform: linux/amd64
    command: serve --model TabbyML/T5P-220M
    volumes:
      - "$HOME/.tabby:/data"
